config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :tags
  resources :categories
  devise_for :users, :controllers => {:confirmations => 'confirmations'}
  resources :announcements, except: :destroy
  match "gems", to: "laser_gems#index" , via: [:get, :post] , as: :laser_gems
  post 'gem/:name/add_tag', to: 'laser_gems#add_tag', as: :add_tag
  post 'gem/:name/add_comment', to: 'laser_gems#add_comment', as: :add_comment
  get   "gem/:name"  , to: "laser_gems#show" , as: :laser_gem
  get 'owners/index', to: 'owners#index', as: :owners_index

  root to: "main#home"
  get '/logo', to: 'main#logo', as: 'logo'
  get '/about', to: 'main#about', as: 'about'
  get '/faq', to: 'main#faq', as: 'faq'
  get '/contribute', to: 'main#contribute', as: 'contribute'
  get '/updates/show', to: 'updates#show', as:'updates_show'
  get '/updates/bounce/:gem_name', to: 'updates#bounce', as:'updates_bounce'
  post '/updates/update', to: 'updates#update', as: 'updates'

  #legacy
  get '/laser_gems',to: redirect("/gems")
  get '/laser_gem/:id',   to: redirect { |params, req| "/gem/#{params[:id]}" }

  authenticate :user, lambda { |u| u and u.admin? } do
    mount Sidekiq::Web => '/karate'
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord

  validates :title, length: { in: 5..30}, presence: true
  validates :body, length: {minimum: 10, maximum: 3000}, presence: true

  belongs_to :user , required: true

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:new, :edit, :update]
  before_action :require_admin_rights, only: [:new, :edit, :update]

  impressionist

  # GET /announcements
  def index
    @announcements = Announcement.all
    if Announcement.first == nil
      @empty = true
    else
      @empty = false
    end
  end

  # GET /announcements/1
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.user = current_user

    if @announcement.save
      redirect_to @announcement, notice: 'Announcement was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /announcements/1
  def update
    if @announcement.update(announcement_params)
      redirect_to @announcement, notice: 'Announcement was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def announcement_params
      params.require(:announcement).permit(:title, :body)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.haml
.announcement_form
  = simple_form_for(@announcement, html: { class: 'form-horizontal' }) do |f|
    - if @announcement.errors.any?
      #error_explanation
        %h2= "#{pluralize(@announcement.errors.count, "error")} prohibited this announcement from being saved:"

    = f.input :title
    = f.input :body, input_html: { rows: "10" }
    = f.button :submit

app/views/announcements/edit.html.haml
.announcement_new_or_edit
  %h1 Editing announcement

  = render 'form'

  %ul.pager
    %li= link_to 'Show', @announcement
    %li= link_to 'Back', announcements_path

app/views/announcements/index.html.haml
.announcement_index
  %h1 Announcements
  - if !@empty
    = link_to 'New Announcement', new_announcement_path, class: 'btn btn-primary'
    - @announcements.each do |announcement|
      .card
        .card-header
          %span.tag.tag-pill.tag-default.align-top
            = link_to 'Edit', edit_announcement_path(announcement)
          %span.h3
            = announcement.title
            %small.text-muted.pl-1
              = time_ago_in_words announcement.created_at
              ago
        .card-block
          %p.card-text
            = truncate(announcement.body, length: 500, separator: ' ', omission: '... ') do
              = link_to 'more', announcement
  - else
    .card
      .card-header
        = link_to 'New Announcement', new_announcement_path, class: 'btn btn-primary'
      .card-block
        %p.card-text No announcements to show

app/views/announcements/new.html.haml
.announcement_new_or_edit
  %h1 New announcement

  = render 'form'

  %ul.pager
    %li= link_to 'Back', announcements_path

app/views/announcements/show.html.haml
%p#notice= notice
.announcement_show
  = link_to 'Edit', edit_announcement_path(@announcement), class: 'btn btn-primary'
  .card
    %h3.card-header
      = @announcement.title
      %small.text-muted.date
        = time_ago_in_words @announcement.created_at
        ago
    .card-block
      %p.card-text= @announcement.body
  = link_to 'Go back', announcements_path, class: 'btn btn-primary'