config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :tags
  resources :categories
  devise_for :users, :controllers => {:confirmations => 'confirmations'}
  resources :announcements, except: :destroy
  match "gems", to: "laser_gems#index" , via: [:get, :post] , as: :laser_gems
  post 'gem/:name/add_tag', to: 'laser_gems#add_tag', as: :add_tag
  post 'gem/:name/add_comment', to: 'laser_gems#add_comment', as: :add_comment
  get   "gem/:name"  , to: "laser_gems#show" , as: :laser_gem
  get 'owners/index', to: 'owners#index', as: :owners_index

  root to: "main#home"
  get '/logo', to: 'main#logo', as: 'logo'
  get '/about', to: 'main#about', as: 'about'
  get '/faq', to: 'main#faq', as: 'faq'
  get '/contribute', to: 'main#contribute', as: 'contribute'
  get '/updates/show', to: 'updates#show', as:'updates_show'
  get '/updates/bounce/:gem_name', to: 'updates#bounce', as:'updates_bounce'
  post '/updates/update', to: 'updates#update', as: 'updates'

  #legacy
  get '/laser_gems',to: redirect("/gems")
  get '/laser_gem/:id',   to: redirect { |params, req| "/gem/#{params[:id]}" }

  authenticate :user, lambda { |u| u and u.admin? } do
    mount Sidekiq::Web => '/karate'
  end
end

app/models/laser_gem.rb
class LaserGem < ApplicationRecord
  validates :name, length: { in: 2..90}, format: { without: /\s/, message: "must contain no spaces" }
  validates_uniqueness_of :name

  has_many :gem_dependencies
  has_many :dependencies, :through => :gem_dependencies

  has_many :gem_dependents, class_name: "GemDependency", foreign_key: :dependency_id
  has_many :dependents, :through => :gem_dependents, source: :laser_gem

  has_many :comments

  has_one :gem_spec
  has_one :gem_git , inverse_of: :laser_gem

  has_many :ownerships
  has_many :owners, :through => :ownerships, :foreign_key => "laser_gem_id", :source => "owner"

  belongs_to :category

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  is_impressionable

  default_scope { order(total_rank: :desc) }

  def home_page
    gem_spec.home_page
  end

  def is_gem_owner?( user )
    return false unless user
    self.ownerships.any? {|o| o.owner ==  user }
  end
  #
  # Add a gem as a dependency of this one.
  #
  def register_dependency(dep, version)
    GemDependency.create!(
      laser_gem: self,
      dependency: dep,
      version: version,
    )
    self.reload
  end

  #
  # Remove a dependency
  #
  def remove_dependency(dep)
    GemDependency.where(
      laser_gem: self,
      dependency: dep,
    ).destroy_all
    self.reload
  end
end

app/controllers/laser_gems_controller.rb
class LaserGemsController < ApplicationController
  include ApplicationHelper

  before_action :authenticate_user!,   only: [:add_comment , :add_tag]
  before_action :load_gem ,            only: [:show ,   :add_tag , :add_comment]

  impressionist actions: [ :index , :add_tag , :add_comment ]

  # GET /laser_gems
  def index
    @q = LaserGem.includes(:gem_spec, :gem_git, :taggings => :tag).
                  joins( :gem_spec ).
                  ransack(params[:q])
    @laser_count = @q.result(distinct: true)
    page = params[:page].to_i
    page = 1 if page < 1 or page > 20
    @laser_gems = @laser_count.paginate(page: page, per_page: 20)

    respond_to do |format|
      format.html
      format.js
    end
  end
  # GET /laser_gems/gem_name
  def show
    redirect_to(root_path) unless (@laser_gem and @laser_gem.gem_spec)
    impressionist(@laser_gem) if @laser_gem
  end

  def add_tag
    if msg = tag_validation( params[:tag] )
      flash[:notice] = "Please insert a valid tag. " + msg
      render :show
    else
      @laser_gem.tag_list.add(params[:tag])
      @laser_gem.save
      redirect_to laser_gem_path(@laser_gem.name)
    end
  end

  def add_comment
    @comment = Comment.new(body: params[:comment_body], user: current_user, laser_gem: @laser_gem)
    if @comment.save
      redirect_to laser_gem_path(@laser_gem.name)
    else
      flash[:notice] = "Please insert a valid comment."
      render :show
    end
  end

  def has_owner_rights?
    return false unless current_user
    @laser_gem.is_gem_owner?(current_user)
  end
  helper_method :has_owner_rights?

  private

  def load_gem
    @laser_gem = LaserGem.find_by_name(params[:name])
  end

end

app/helpers/laser_gems_helper.rb
module LaserGemsHelper
  def k_numbers(number)
    return "#{number / 1000000}M" if number > 1000000
    return "#{number / 1000}k" if number > 1000
    number.to_s
  end

  def tags_cloud
    ActsAsTaggableOn::Tag.most_used(5)
  end

  def link_to_laser laser
    link_to "#{laser.name}(#{rank_to_i laser})", laser_gem_path(laser.name)
  end

  def related_gems laser_gem
    tag = laser_gem.taggings.collect{|t| t.tag}.sort{|t| t.taggings_count}.first
    return [] unless tag
    LaserGem.tagged_with(tag.name).limit(15)
  end

  def tagging_link tagging
    tag = tagging.tag
    link_to("#{tag}(#{tag.taggings_count})", search_tag_url(tag.name))
  end

  #TODO replace from alphabetical order to rank order
  def laser_gems_cloud
    LaserGem.all.includes(:gem_spec).limit(10)
  end

  def search_tag_url tag_name
    q = {}
    q["taggings_tag_name_eq"] = tag_name
    if params[:q].present?
      name = params[:q]["name_or_gem_spec_info_cont"]
      q["name_or_gem_spec_info_cont"]= name if(name)
    end
    laser_gems_path(q: q)
  end

  def max_y
    100.0
  end

  def graph_lines(laser_gem)
    return "" unless laser_gem.gem_git
    return "" if laser_gem.gem_git.commit_dates_year.empty?
    coeff =  max_y / laser_gem.gem_git.commit_dates_year.max
    result = "0,#{max_y}\n"
    laser_gem.gem_git.commit_dates_year.each_with_index do |val , index|
      result << "#{6*index},#{max_y - val*coeff - 2 }\n"
    end
    result
  end

  def total_commits laser_gem
    return 0 unless laser_gem.gem_git
    return 0 if laser_gem.gem_git.commit_dates_year.empty?
    laser_gem.gem_git.commit_dates_year.sum
  end

  def chart_options_long
    { height: "200px",
      ytitle: "Commits per Week",
      label: "Commits per Week",
      library: { plotOptions: { series: { lineColor: '#3b5f7c' } },
        xAxis: { tickInterval: 8153600000, title: { text: "Date" } }
      }
    }
  end

  def chart_options_short
    { height: "150px",
      ytitle: "Commits",
      label: "Commits",
      library: { plotOptions: { series: { lineColor: '#3b5f7c' } },
        xAxis: { title: { enabled: false } , labels: {enabled: false}}
      }
    }
  end

  def activity_chart(laser_gem , type = :long)
    return "" unless laser_gem and laser_gem.gem_git
    options = send "chart_options_#{type}".to_sym
    weeks =  52.times.collect{|i| (Time.now - i.weeks).to_date }.reverse
    commit_act = laser_gem.gem_git.commit_dates_year
    line_chart(weeks.zip(commit_act) , options )
  end
end

app/views/laser_gems/_index_graph.haml
.graph_box
  %svg{:viewbox => "0 0 315 #{max_y}" , class:  :index_graph}
    %polyline{:fill => "none", :points => "#{graph_lines(laser_gem)}" , :stroke => "#0074d9", "stroke-linejoin" => "round", "stroke-width" => "3" }

app/views/laser_gems/_laser_gem.html.haml
.gem_element
  .card
    %h5.card-header
      .index-card-left
        = link_to laser_gem.name, laser_gem_path(laser_gem.name)
        %small.text-muted
          = laser_gem.gem_spec.current_version
      .index-card-right
        %small.text-muted
          %i.fa.fa-trophy.tipit{ :title => "Total rank for this gem"}
          = rank_to_i laser_gem
    .card-block.tipster
      %p.card-text
        %small.small_info
          = truncate(laser_gem.gem_spec.info, length: 90, separator: ' ', omission: '... ')
        .whole_info
          = truncate(laser_gem.gem_spec.info, length: 300, separator: ' ')
        - if laser_gem.gem_git
          %p.card-text.text-xs-center
            .graph_box
              %svg{:viewbox => "0 0 315 #{max_y}" , class:  :index_graph}
                %polyline{:fill => "none", :points => "#{graph_lines(laser_gem)}" , :stroke => "#0074d9", "stroke-width" => "3"}
            = pluralize(total_commits(laser_gem), "commit", plural: "commits")
            this year.
      %p.card-text
        -laser_gem.taggings.each do |tagging|
          %span.tag.tag-default= tagging_link(tagging)
    .card-block.stats
      %span.card-link
        %i.fa.fa-arrow-circle-down{"aria-hidden": "true"}
        =k_numbers laser_gem.gem_spec.total_downloads
      - if laser_gem.gem_git
        %span.card-link
          %i.fa.fa-code-fork{"aria-hidden" => "true"}
          = k_numbers laser_gem.gem_git.forks_count
        %span.card-link
          %i.fa.fa-star{"aria-hidden" => "true"}
          = k_numbers laser_gem.gem_git.stargazers_count
        %span.card-link
          %i.fa.fa-eye{"aria-hidden" => "true"}
          = k_numbers laser_gem.gem_git.watchers_count
        %span.card-link
          %i.fa.fa-flag{"aria-hidden" => "true"}
          = k_numbers laser_gem.gem_git.open_issues_count

app/views/laser_gems/index.html.haml
.index
  .search
    .card
      .card-block
        .searchbox
          = search_form_for @q, method: :get  , class: "form-inline" do |f|
            .form_group
              = f.search_field :gem_spec_name_or_gem_spec_info_cont , placeholder: "Search Text" , autofocus: true , class: "form-control"
              = f.search_field :taggings_tag_name_eq , placeholder: "Search by tag", class: "form-control"
              = f.button "Search" , :value => "Search" ,  class: :btn
              %span.text-muted
                = pluralize(@laser_count.count, "gem", plural: "gems")
        .order
          Sort:
          = sort_link(@q, "total_rank" , default_order: :desc) do
            %i.fa.fa-trophy.tipit{ :title => "Sort by rank"}
          = sort_link(@q, "gem_spec_total_downloads" , default_order: :desc) do
            %i.fa.fa-arrow-circle-down.tipit{ :title => "Sort by downloads"}
          = sort_link(@q, "gem_git_last_commit" , default_order: :desc) do
            %i.fa.fa-clock-o.fa-fw.tipit{ :title => "Sort by last commit"}
          = sort_link(@q, "gem_git_stargazers_count" , default_order: :desc) do
            %i.fa.fa-star.tipit{ :title => "Sort by stargazers"}
          = sort_link(@q, "gem_git_watchers_count" , default_order: :desc) do
            %i.fa.fa-eye.tipit{ :title => "Sort by watchers"}
          = sort_link(@q, "gem_git_forks_count" , default_order: :desc) do
            %i.fa.fa-code-fork.tipit{ :title => "Sort by fork count"}


  .results
    .gem_pages#gem_pages
      =render @laser_gems
    .infinite-scrolling
      = will_paginate @laser_gems, :renderer => WillPaginate::ActionView::BootstrapLinkRenderer

app/views/laser_gems/index.js.erb
$('.gem_pages').append('<%= j render @laser_gems %>');
<% if @laser_gems.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @laser_gems %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/laser_gems/show.html.haml
.gem_show_left
  .card
    %h4.card-header
      .header-left
        = @laser_gem.name
        %small.text-muted.pl-1
          = @laser_gem.gem_spec.current_version
      .header-right.small
        %i.fa.fa-trophy.fa-fw{"aria-hidden" => "true"}
        = rank_to_i @laser_gem
    .card-block
      %p.card-text
        = @laser_gem.gem_spec.info
      %p.card-text
        - @laser_gem.taggings.each do |tagging|
          %span.tag.tag-default= tagging_link(tagging)
        - if current_user
          = form_tag(add_tag_path(@laser_gem.name)) do
            = text_field_tag(:tag)
            %button.icon{id: "save_tag", type: "submit"}
              +
      %p.card-text.text-xs-right
        %span.card-link
          = link_to( @laser_gem.gem_spec.rubygem_uri, :target => "_blank") do
            =image_tag "rubygems_logo.png" , width: "20px" , height: "20px"
            RubyGems
        %span.card-link
          %i.fa.fa-file-text-o.fa-fw{"aria-hidden" => "true"}
          = link_to("Source code", @laser_gem.home_page, :target => "_blank")
        %span.card-link
          %i.fa.fa-book.fa-fw{"aria-hidden" => "true"}
          = link_to("Documentation", @laser_gem.gem_spec.documentation_uri, :target => "_blank")

  .card
    .card-header Related gems
    .card-block
      %p.card-text
        -if @laser_gem.find_related_tags.limit(15).first
          -related_gems(@laser_gem).each do |laser|
            =link_to_laser laser
        -else
          Sorry, we are not able to find any related gems.

  - if @laser_gem.dependents != nil
    .card
      .card-header Dependents
      .card-block
        %p.card-text
        - if @laser_gem.dependents.first
          - @laser_gem.dependents.limit(15).each do |dependent|
            = link_to_laser dependent
        - else
          This gem has no dependents.


  .card
    .card-header Dependencies
    .card-block
      %p.card-text
        - if @laser_gem.dependencies.first
          - @laser_gem.dependencies.limit(15).each do |dependency|
            = link_to_laser dependency
        - else
          This gem has no dependencies.

  .comments
    %h3
      Comments
      %i.fa.fa-comments-o.fa-lg.fa-fw{"aria-hidden": "true"}
    - if @laser_gem.comments.any?
      - @laser_gem.comments.each do |comment|
        %h5
          %i.fa.fa-user-circle-o.fa-lg.fa-fw{"aria-hidden": "true"}
          = comment.user.name
          %small.text-muted
            =time_ago_in_words comment.created_at
            ago
        .comment_body
          = comment.body
    - else
      No comments to show.
    - flash.each do |name, message|
      .comment_error
        =message
    - if current_user
      = form_tag(add_comment_path(@laser_gem.name)) do
        .field
          = text_area_tag(:comment_body)
        %button.btn.btn-secondary{id: "add_comment", type: "submit", method: :post} Add Comment

.gem_show_right
  .card
    .card-header
      %i.fa.fa-arrow-circle-down.fa-fw{"aria-hidden": "true"}
      Downloads
    .card-block
      %p.card-text
        This version:
        = k_numbers @laser_gem.gem_spec.current_version_downloads
      -if @laser_gem.gem_spec.current_version_creation
        %p.card-text
          Released
          = time_ago_in_words(@laser_gem.gem_spec.current_version_creation)
          ago
      %p.card-text
        Total:
        = k_numbers @laser_gem.gem_spec.total_downloads
      %p.card-text
        = @laser_gem.download_rank_string

  .card
    .card-header
      %i.fa.fa-heartbeat.fa-fw{"aria-hidden" => "true"}
      Activity
    - if @laser_gem.gem_git != nil
      .card-block
        %p.card-text
          = activity_chart(@laser_gem)
    .card-footer
      -if @laser_gem.gem_spec.build_date
        %i.fa.fa-calendar-plus-o.fa-fw{"aria-hidden": "true"}
        Created
        = time_ago_in_words(@laser_gem.gem_spec.build_date)
        ago

  - if @laser_gem.gem_git != nil
    .card
      .card-header
        %i.fa.fa-github.fa-fw{"aria-hidden" => "true"}
        GitHub stats
      .card-block
        %p.card-text
          %i.fa.fa-clock-o.fa-fw{"aria-hidden" => "true"}
          Last commit:
          = time_ago_in_words @laser_gem.gem_git.last_commit
          ago
        %p.card-text
          %i.fa.fa-code-fork.fa-fw{"aria-hidden" => "true"}
          Forks:
          = @laser_gem.gem_git.forks_count
        %p.card-text
          %i.fa.fa-star.fa-fw{"aria-hidden" => "true"}
          Stargazers:
          = @laser_gem.gem_git.stargazers_count
        %p.card-text
          %i.fa.fa-eye.fa-fw{"aria-hidden" => "true"}
          Watchers:
          = @laser_gem.gem_git.watchers_count
        %p.card-text
          %i.fa.fa-flag.fa-fw{"aria-hidden" => "true"}
          Open issues:
          = @laser_gem.gem_git.open_issues_count

  .card
    .card-header Authors
    .card-block
      %p.card-text
        = truncate(@laser_gem.gem_spec.authors, length: 200, separator: ' ', omission: '... ')