config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :tags
  resources :categories
  devise_for :users, :controllers => {:confirmations => 'confirmations'}
  resources :announcements, except: :destroy
  match "gems", to: "laser_gems#index" , via: [:get, :post] , as: :laser_gems
  post 'gem/:name/add_tag', to: 'laser_gems#add_tag', as: :add_tag
  post 'gem/:name/add_comment', to: 'laser_gems#add_comment', as: :add_comment
  get   "gem/:name"  , to: "laser_gems#show" , as: :laser_gem
  get 'owners/index', to: 'owners#index', as: :owners_index

  root to: "main#home"
  get '/logo', to: 'main#logo', as: 'logo'
  get '/about', to: 'main#about', as: 'about'
  get '/faq', to: 'main#faq', as: 'faq'
  get '/contribute', to: 'main#contribute', as: 'contribute'
  get '/updates/show', to: 'updates#show', as:'updates_show'
  get '/updates/bounce/:gem_name', to: 'updates#bounce', as:'updates_bounce'
  post '/updates/update', to: 'updates#update', as: 'updates'

  #legacy
  get '/laser_gems',to: redirect("/gems")
  get '/laser_gem/:id',   to: redirect { |params, req| "/gem/#{params[:id]}" }

  authenticate :user, lambda { |u| u and u.admin? } do
    mount Sidekiq::Web => '/karate'
  end
end

app/views/layouts/_footer.html.haml
.footer
  .menu
    %ul.list-unstyled
      %li
        = link_to 'About LASER', about_path
      %li
        = link_to 'F.A.Q.', faq_path
      %li
        = link_to 'Contribute', contribute_path
      %li
        = link_to 'Add or Update Gem', updates_show_path
  .sponsor
    Sponsored by Web Dev Camp
    %br
    = link_to(image_tag("webdevcamp.png", class: "img-fluid"), 'http://webdev.camp/', :target => "_blank")
  .links
    %ul.list-unstyled
      %li
        =link_to("https://github.com/webdev-camp/laser", :target => "_blank") do
          %i.fa.fa-github-alt.fa-2x.fa-fw{"aria-hidden" => "true"}
          GitHub
      %li
        =link_to("https://www.facebook.com/webdev.camp", :target => "_blank") do
          %i.fa.fa-facebook-square.fa-2x.fa-fw{"aria-hidden" => "true"}
          Facebook

app/views/layouts/_header.html.haml
.header
  %nav.responsive-navbar
    %button.menu-button{"data-target" => "#mainNavbarCollapse", "data-toggle" => "collapse", :type => "button"}
      ☰
    %a.laser-logo{:href => "/"}
      = render 'layouts/logo'
    #mainNavbarCollapse.collapse-toggle
      %ul.navbar-ul
        %li.nav-item
          .nav-link= link_to "LASER", root_path
          %span.sr-only (current)
        %li.nav-item
          .nav-link= link_to "Gems", laser_gems_path
        %li.nav-item
          .nav-link= link_to "Tags", tags_path
      %ul.navbar-ul.pull-right
        %li.nav-item.pull-right
          -if user_signed_in?
            %li.nav-item
              .nav-link= link_to "Log Out", destroy_user_session_path, :method => 'delete'
          -else
            %li.nav-item
              .nav-link= link_to "Log In", new_user_session_path
            %li.nav-item
              .nav-link= link_to "Sign Up", new_user_registration_path

app/views/layouts/_html_head.html.haml
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%title Laser
= csrf_meta_tags
%meta{:content => "width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0", :name => "viewport"}
= stylesheet_link_tag 'application', media: 'all'
= javascript_include_tag 'application'
%link{href: "https://fonts.googleapis.com/css?family=Pattaya|Raleway:900i|Timmana", rel:"stylesheet"}
%link{href: "https://fonts.googleapis.com/css?family=Courgette", rel:"stylesheet"}
= yield :html_head
-if Rails.env.production?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    var the_id = 'UA-76401513-1';
    ga('create', the_id.replace("-1" , "-4") , 'auto');
    ga('send', 'pageview');

app/views/layouts/_logo.html.haml
.logo.style1.style2
  %svg{:height => "40px", :viewbox => "0 0 40 40", :width => "40px"}
    %defs
      %lineargradient#Gradient-1{:x1 => "0", :x2 => "100%", :y1 => "0", :y2 => "0"}
        %stop{:offset => "0%", "stop-color" => "lightred"}
        %stop{:offset => "100%", "stop-color" => "#ef5b2b"}

      %lineargradient#Gradient-2{:x1 => "0", :x2 => "100%", :y1 => "0", :y2 => "0"}
        %stop{:offset => "0%", "stop-color" => "#ffff66"}
        %stop{:offset => "50%", "stop-color" => "#ffffe6"}
        %stop{:offset => "100%", "stop-color" => "#ffffff"}

    %polygon.tri1.left{:fill => "url(#Gradient-1)", :points => "0,8.66 5,0 10,8.66", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.tri2.left{:fill => "url(#Gradient-1)", :points => "7.5,0 12.5,8.66 17.5,0", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.tri3.center{:fill => "url(#Gradient-1)", :points => "20,0 15,8.66 25,8.66", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.tri4.right{:fill => "url(#Gradient-1)", :points => "22.5,0 27.5,8.66 32.5,0", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.tri5.right{:fill => "url(#Gradient-1)", :points => "35,0 30,8.66 40,8.66", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.bigtri1.left{:fill => "url(#Gradient-1)", :points => "0,10 17.5,40 12.5,10", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.bigtri2.center{:fill => "url(#Gradient-1)", :points => "15,10 20,40 25,10", :stroke => "#FF8A65", "stroke-width" => "0.4"}
    %polygon.bigtri3.right{:fill => "url(#Gradient-1)", :points => "27.5,10 22.5,40 40,10", :stroke => "#FF8A65", "stroke-width" => "0.4"}

    %polygon.thunderbolt{:fill => "url(#Gradient-2)", :points => "20,0 10,22.5 20,22.5 20,40 30,17.5 20,17.5", :stroke => "#FF8A65", "stroke-width" => "0.4"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/html_head'
  %body
    = render 'layouts/header'
    .content
      =yield
    = render 'layouts/footer'